# Generated by Django 5.1.4 on 2025-01-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0002_alter_order_total_price_alter_payment_status_and_more'),
    ]

    operations = [
    ]
