# Generated by Django 5.1.4 on 2025-01-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0003_auto_20250106_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.category'),
            preserve_default=False,
        ),
    ]
