# Generated by Django 5.1.4 on 2025-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0004_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_unit',
            field=models.CharField(choices=[('uzs', 'usd')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
