# Generated by Django 5.1.4 on 2025-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0005_product_product_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price_unit',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=5),
        ),
    ]
